//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMultiCommitTest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long CustomerSN { get; set; }
        public string Company { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string RegisteredAddress { get; set; }
        public string CustomerAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Flag { get; set; }
        public string DelFlag { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateIp { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateIp { get; set; }
        public string CustomerLevel { get; set; }
    }
}
